language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.6.3
    - DRUPAL8=8.6.0
    - DRUPAL7=7.59
    - DRUPAL6=6.38
  matrix:
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.2 TAGS=8-7.2,8,latest
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.1 TAGS=8-7.1
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.0 TAGS=8-7.0
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.2 TAGS=7-7.2,7
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.1 TAGS=7-7.1
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.0 TAGS=7-7.0
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=5.6 TAGS=7-5.6
    - DRUPAL_VER="${DRUPAL6}" PHP_VER=5.6 TAGS=6-5.6,6
    - DRUPAL_VER="${DRUPAL6}" PHP_VER=5.3 TAGS=6-5.3

script:
  - set -e
  - cd "${DRUPAL_VER%%.*}"
  - make check-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
