language: python

services:
  - docker

env:
  matrix:
    - DRUPAL=8 SERVICE=nginx
    - DRUPAL=7 SERVICE=nginx

install:
  - cd ./$DRUPAL/$SERVICE
  - make

script: make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make VERSION="$TRAVIS_TAG" release
    fi

    if [ "$VERSION" == "8" ]; then
      make VERSION=latest release
    fi
  fi

after_failure:
  - make logs

notifications:
  email:
    on_success: never
