language: python

sudo: required

services:
  - docker

env:
  global:
    - REPO=wodby/drupal-php
    - LATEST_DRUPAL=8
    - LATEST_PHP_VER=7.1
  matrix:
    - DRUPAL=8 PHP_VER=7.1 PHP_DEBUG=0
    - DRUPAL=8 PHP_VER=7.0 PHP_DEBUG=0
    - DRUPAL=7 PHP_VER=7.1 PHP_DEBUG=0
    - DRUPAL=7 PHP_VER=7.0 PHP_DEBUG=0
    - DRUPAL=7 PHP_VER=5.6 PHP_DEBUG=0
    - DRUPAL=6 PHP_VER=5.6 PHP_DEBUG=0
    - DRUPAL=6 PHP_VER=5.3 PHP_DEBUG=0
    - DRUPAL=8 PHP_VER=7.1 PHP_DEBUG=1
    - DRUPAL=8 PHP_VER=7.0 PHP_DEBUG=1
    - DRUPAL=7 PHP_VER=7.1 PHP_DEBUG=1
    - DRUPAL=7 PHP_VER=7.0 PHP_DEBUG=1
    - DRUPAL=7 PHP_VER=5.6 PHP_DEBUG=1
    - DRUPAL=6 PHP_VER=5.6 PHP_DEBUG=1

script:
  - cd ./$DRUPAL/"${PHP_VER:0:1}"
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make TAG="$DRUPAL-$PHP_VER-$TRAVIS_TAG" release
    fi

    if [ "$DRUPAL" == "$LATEST_DRUPAL" && "$PHP_VER" == "$LATEST_PHP_VER" && $PHP_DEBUG != 1 ]; then
      make TAG=latest release
    fi
  fi
