language: bash

services:
  - docker

env:
  global:
    - GIT_MERGE_SEPARATOR_DUMMY_ENV_VAR=1
    - DRUPAL8=8.6.13
    - DRUPAL7=7.65
  matrix:
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.3 TAGS=8-7.3,8-7,8,latest
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.2 TAGS=8-7.2
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.1 TAGS=8-7.1
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.3 TAGS=7-7.3,7-7,7
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.2 TAGS=7-7.2
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.1 TAGS=7-7.1
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=5.6 TAGS=7-5.6,7-5

script:
  - set -e
  - cd "${DRUPAL_VER%%.*}"
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
      - $NOTIFICATIONS_EMAIL
    on_success: never
    on_failure: always

