language: bash

services:
- docker

env:
  global:
  - GIT_MERGE_SEPARATOR_DUMMY_ENV_VAR=1
  - DRUPAL9=9.0.0
  - DRUPAL8=8.9.0
  - DRUPAL7=7.71
  matrix:
  - DRUPAL_VER="${DRUPAL9}" PHP_VER=7.4 TAGS=9-7.4,9-7,9,latest
  - DRUPAL_VER="${DRUPAL9}" PHP_VER=7.3 TAGS=9-7.3
  - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.4 TAGS=8-7.4,8-7,8
  - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.3 TAGS=8-7.3
  - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.2 TAGS=8-7.2
  - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.4 TAGS=7-7.4,7-7,7
  - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.3 TAGS=7-7.3
  - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.2 TAGS=7-7.2

script:
- set -e
- cd "${DRUPAL_VER%%.*}"
- make
- make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
