language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.8.2
    - DRUPAL8=8.6.1
    - DRUPAL7=7.59
  matrix:
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.2 TAGS=8-7.2,8,latest
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.1 TAGS=8-7.1
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.2 TAGS=7-7.2,7
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.1 TAGS=7-7.1
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=5.6 TAGS=7-5.6

script:
  - set -e
  - cd "${DRUPAL_VER%%.*}"
  - make check-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
