language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=8-7.1
    - BASE_IMAGE_STABILITY_TAG=4.4.1
  matrix:
    - TAG=8-7.1 DRUPAL=8 PHP_VER=7.1 EXTRA_TAG=8
    - TAG=8-7.0 DRUPAL=8 PHP_VER=7.0
    - TAG=7-7.1 DRUPAL=7 PHP_VER=7.1 EXTRA_TAG=7
    - TAG=7-7.0 DRUPAL=7 PHP_VER=7.0
    - TAG=7-5.6 DRUPAL=7 PHP_VER=5.6
    - TAG=6-5.6 DRUPAL=6 PHP_VER=5.6 EXTRA_TAG=6
    - TAG=6-5.3 DRUPAL=6 PHP_VER=5.3

script:
  - set -e
  - cd "${DRUPAL}"
  - make check-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
