language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.9.1
    - DRUPAL8=8.6.3
    - DRUPAL7=7.61
  matrix:
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.2 TAGS=8-7.2,8-7,8,latest
    - DRUPAL_VER="${DRUPAL8}" PHP_VER=7.1 TAGS=8-7.1
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.2 TAGS=7-7.2,7-7,7
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=7.1 TAGS=7-7.1
    - DRUPAL_VER="${DRUPAL7}" PHP_VER=5.6 TAGS=7-5.6,7-5

script:
  - set -e
  - cd "${DRUPAL_VER%%.*}"
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
      - $NOTIFICATIONS_EMAIL
    on_success: never
    on_failure: always
