language: bash

services:
  - docker

env:
  matrix:
    - DRUPAL=8 PHP_VER=7.2 TAGS=8-7.2,8,latest
    - DRUPAL=8 PHP_VER=7.1 TAGS=8-7.1
    - DRUPAL=8 PHP_VER=7.0 TAGS=8-7.0
    - DRUPAL=7 PHP_VER=7.2 TAGS=7-7.2,7
    - DRUPAL=7 PHP_VER=7.1 TAGS=7-7.1
    - DRUPAL=7 PHP_VER=7.0 TAGS=7-7.0
    - DRUPAL=7 PHP_VER=5.6 TAGS=7-5.6
    - DRUPAL=6 PHP_VER=5.6 TAGS=6-5.6,6
    - DRUPAL=6 PHP_VER=5.3 TAGS=6-5.3

script:
  - set -e
  - cd "${DRUPAL}"
  - make check-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
