language: bash

sudo: required

services:
  - docker

env:
  global:
    - DOCKER_VERSION=17.06.2
    - LATEST_TAG=8-7.1
    - FROM_STABILITY_TAG=
  matrix:
    - TAG=8-7.1 DRUPAL=8 PHP_VER=7.1
    - TAG=8-7.0 DRUPAL=8 PHP_VER=7.0
    - TAG=7-7.1 DRUPAL=7 PHP_VER=7.1
    - TAG=7-5.6 DRUPAL=7 PHP_VER=7.0
    - TAG=7-5.3 DRUPAL=7 PHP_VER=5.6
    - TAG=6-5.6 DRUPAL=6 PHP_VER=5.6
    - TAG=6-5.3 DRUPAL=6 PHP_VER=5.3
    - TAG=8-7.1-dev DRUPAL=8 PHP_VER=7.1 PHP_DEV=1
    - TAG=8-7.0-dev DRUPAL=8 PHP_VER=7.0 PHP_DEV=1
    - TAG=7-7.1-dev DRUPAL=7 PHP_VER=7.1 PHP_DEV=1
    - TAG=7-7.0-dev DRUPAL=7 PHP_VER=7.0 PHP_DEV=1
    - TAG=7-5.6-dev DRUPAL=7 PHP_VER=5.6 PHP_DEV=1
    - TAG=6-5.6-dev DRUPAL=6 PHP_VER=5.6 PHP_DEV=1

install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce="${DOCKER_VERSION}~ce-0~ubuntu"

script:
  - cd ./"${DRUPAL}"
  - make && make test

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

    if [[ -n "${TRAVIS_TAG}" ]]; then
      export STABILITY_TAG="${TRAVIS_TAG}"
    fi

    make release

    if [[ "${TAG}" == "${LATEST_TAG}" ]]; then
      make release TAG="latest"
    fi
  fi
