language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=8-7.1
    - DRUPAL8=8.4.5
    - DRUPAL7=7.57
    - DRUPAL6=6.38
  matrix:
    - TAG=8-7.1 DRUPAL_VER="${DRUPAL8}" PHP_VER=7.1
    - TAG=8-7.0 DRUPAL_VER="${DRUPAL8}" PHP_VER=7.0
    - TAG=7-7.1 DRUPAL_VER="${DRUPAL7}" PHP_VER=7.1
    - TAG=7-7.0 DRUPAL_VER="${DRUPAL7}" PHP_VER=7.0
    - TAG=7-5.6 DRUPAL_VER="${DRUPAL7}" PHP_VER=5.6
    - TAG=6-5.6 DRUPAL_VER="${DRUPAL6}" PHP_VER=5.6
    - TAG=6-5.3 DRUPAL_VER="${DRUPAL6}" PHP_VER=5.3

script:
  - set -e
  - cd ./"${DRUPAL_VER:0:1}"
  - make compare-orig-configs
  - make
  - make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
